### ISSUE TITLE
[FEAT]: Print 3D part(s) to connect LEGO parts to Mini Pupper 2

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/FREISA#19]
### Description

From Afreez message on Discord group "general" of Pupper@MangDang, 2024-02-19:

![image](https://github.com/B-AROL-O/FREISA/assets/75182/4ffa68f8-aa63-4426-84a5-e236f4958b21)

**Comment by gmacario** [comment]
After a quick message exchange over discord I agreed with Afreez the following process

![image](https://github.com/B-AROL-O/FREISA/assets/75182/ad5fd10f-4ebf-422b-87e5-d7d4ac2bd7fb)

In summary:

* The STL have already been published by @MangDangroboticsclub on Google Drive: https://drive.google.com/drive/folders/1TTmcGOG-JoAWNTGy1r7hbb7txhZIF4_p
* If someone needs to modify them, the updates will eventually be shared as PR to https://github.com/B-AROL-O/FREISA

**Comment by gmacario** [comment]
And here is a photo of the first attempt made by @OrsoEric to 3D-print those parts using his [Creality K1 3D Printer](https://www.creality.com/products/creality-k1-3d-printer)

![2024-03-13 19 46 13](https://github.com/B-AROL-O/FREISA/assets/75182/ed01e985-58a2-40ad-82f0-d2e521342267)

**Comment by gmacario** [comment]
Here is a second 3D-print attempt, this time with a [Yellow PLA](https://www.amazon.it/gp/product/B07QQBY6PL)

![photo_6025941113627590385_y](https://github.com/B-AROL-O/FREISA/assets/75182/1c236be8-36f5-4c28-8526-83f127872801)

**Comment by gmacario** [comment]
However the best results have been achieved with this Red PLA

![photo_6025941113627590386_y](https://github.com/B-AROL-O/FREISA/assets/75182/15b9a810-52b5-4c1c-b928-5abc4113c5cc)

**Comment by gmacario** [comment]
Here is our FREISA doggo after attaching the LEGO parts to it

![photo_6025941113627590387_y](https://github.com/B-AROL-O/FREISA/assets/75182/a8cf712d-fdf0-4bb8-8006-c000b257f0f6)

**Comment by mangdangroboticsclub** [comment]
Cool！

**Comment by gmacario** [comment]
> Cool！

Indeed!
You know, @OrsoEric is **THE** "robot-guy" 😄
